name: M2M_CodeBase
channels:
  - soumith
  - defaults
dependencies:
  - _pytorch_select=0.1=cpu_0
  - blas=1.0=mkl
  - bottleneck=1.3.2
  - brotli=1.0.9
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.14.6
  - cycler=0.10.0=py38_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0
  - giflib=5.2.1
  - intel-openmp=2019.4
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libcxx=12.0.0
  - libffi=3.3
  - libmklml=2019.0.5=0
  - libpng=1.6.37
  - libtiff=4.2.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - llvm-openmp=12.0.0
  - lz4-c=1.9.3
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - munkres=1.1.4=py_0
  - ncurses=6.3
  - ninja=1.10.2
  - numexpr=2.7.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=1.1.1l
  - pandas=1.3.4
  - patsy=0.5.2
  - pillow=8.4.0
  - pip=21.2.4
  - pycparser=2.20=py_2
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - python=3.8.12
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.7.1
  - pytz=2021.3=pyhd3eb1b0_0
  - readline=8.1
  - scikit-learn=1.0.1
  - scipy=1.6.2
  - setuptools=58.0.4
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11
  - tornado=6.1
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
prefix: /Users/jendawk/miniconda3/envs/M2M_CodeBase
